# Shell variables
# Generated by 'wal'
wallpaper="/home/kiroshi/themes/current-wallpaper.jpg"

# Special
background='#0C0B08'
foreground='#c2c2c1'
cursor='#c2c2c1'

# Colors
color0='#0C0B08'
color1='#704B33'
color2='#3E3F40'
color3='#695A48'
color4='#685D4E'
color5='#865036'
color6='#916D52'
color7='#c2c2c1'
color8='#696255'
color9='#704B33'
color10='#3E3F40'
color11='#695A48'
color12='#685D4E'
color13='#865036'
color14='#916D52'
color15='#c2c2c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
