--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kiroshi/themes/current-wallpaper.jpg"

-- Special
background="#0C0B08"
foreground="#c2c2c1"
cursor="#c2c2c1"

-- Colors
color0="#0C0B08"
color1="#704B33"
color2="#3E3F40"
color3="#695A48"
color4="#685D4E"
color5="#865036"
color6="#916D52"
color7="#c2c2c1"
color8="#696255"
color9="#704B33"
color10="#3E3F40"
color11="#695A48"
color12="#685D4E"
color13="#865036"
color14="#916D52"
color15="#c2c2c1"
